spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jg_starter?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: rootpassword
    hikari.initialization-fail-timeout: 0

  # https://flywaydb.org/documentation/callbacks.html
  flyway:
    locations: classpath:/db/migration,/db/devdata

management:
  endpoints:
    web:
      exposure:
        include: "*"

#debug: true

#logging.level.org: DEBUG

app:
  security:
    password-encoder:
      security-strength: 12