server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?createDatabaseIfNotExist=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari.initialization-fail-timeout: 1

  # https://flywaydb.org/documentation/callbacks.html
  flyway:
    locations: classpath:/db/migration,/db/devdata

logging:
  level:
    org.springframework.security: WARN