spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jg_starter?createDatabaseIfNotExist=true
    username: root
    password: rootpassword
    hikari.initialization-fail-timeout: 0

logging:
  level:
    org.springframework.security: INFO


app:
  security:
    password-encoder:
      security-strength: 12